import eventFlyer from '../../src/assets/event/image.png'

import { projects as publicProjects } from '@/app/projects/data'
import type { AdminStore } from '@/lib/admin/types'

export const defaultAdminStore: AdminStore = {
  projects: publicProjects.map((project) => ({
    id: project.slug,
    name: project.name,
    slug: project.slug,
    status: project.status,
    category: project.category,
    primaryImage: project.image,
    galleryImages: project.images ?? [project.image],
    location: project.location,
    summary: project.summary,
    impact: project.impact,
    overview: project.overview,
    details: project.details,
    highlights: project.highlights,
    objectives: project.objectives,
    goal: project.goal,
    raised: project.raised,
    goalSuffix: project.goalSuffix,
    updatedAt: '2026-03-28T08:30:00.000Z',
  })),
  events: [
    {
      id: 'youth-online-seminar-part-three',
      name: 'Youth Online Seminar',
      subtitle: 'Part Three',
      category: 'Upcoming Event',
      host: 'Pastor Brigitte',
      date: 'Sunday 29 March 2026',
      time: '5:30 PM',
      timeAlt: '17:30',
      location: 'Google Meet',
      description: "How To Live The Christian Way In Today's World - Part Three.",
      meetLink: 'https://meet.google.com/kxv-yvzx-kgh',
      flyerImage: eventFlyer,
      featured: true,
      updatedAt: '2026-03-28T08:30:00.000Z',
    },
  ],
  mediaSettings: {
    layout: 'grouped-gallery',
    imageLimitMb: 2,
  },
  mediaAlbums: [
    {
      id: 'worship-moments',
      name: 'Worship Moments',
      description: 'Main service highlights and worship atmosphere.',
      coverImage: '/image.png',
      createdAt: '2026-03-20T09:00:00.000Z',
      images: [
        {
          id: 'worship-1',
          name: 'Main service',
          url: '/image.png',
          sizeKb: 420,
          uploadedAt: '2026-03-20T09:05:00.000Z',
        },
        {
          id: 'worship-2',
          name: 'Project gallery',
          url: '/kingdom-impact-center-1.jpg',
          sizeKb: 355,
          uploadedAt: '2026-03-20T09:07:00.000Z',
        },
      ],
    },
  ],
  members: [
    {
      id: 'member-1',
      firstName: 'Aline',
      lastName: 'Mukamana',
      gender: 'Female',
      maritalStatus: 'Single',
      phone: '0788000001',
      email: 'aline@example.com',
      occupation: 'Teacher',
      nationality: 'Rwandan',
      countryOfResidence: 'Rwanda',
      region: 'Kigali',
      notes: 'Wants to grow in fellowship and serve in worship ministry.',
      photoUrl: '/placeholder-user.jpg',
      createdAt: '2026-03-24T10:10:00.000Z',
      status: 'Pending Review',
    },
    {
      id: 'member-2',
      firstName: 'Samuel',
      lastName: 'Ndayishimiye',
      gender: 'Male',
      maritalStatus: 'Married',
      phone: '0788000002',
      email: 'samuel@example.com',
      occupation: 'Entrepreneur',
      nationality: 'Rwandan',
      countryOfResidence: 'Rwanda',
      region: 'Kigali',
      notes: 'Interested in discipleship and men’s fellowship.',
      photoUrl: '/placeholder-user.jpg',
      createdAt: '2026-03-25T08:20:00.000Z',
      status: 'New',
    },
  ],
  partners: [
    {
      id: 'partner-1',
      organizationName: 'Kingdom Builders Africa',
      contactPerson: 'Grace Uwera',
      phone: '0788000010',
      email: 'grace@kba.org',
      country: 'Rwanda',
      city: 'Kigali',
      partnershipType: 'Outreach Support',
      website: 'https://example.org',
      vision: 'Support outreach and youth discipleship.',
      proposal: 'We would like to support outreach materials and training activities.',
      logoUrl: '/placeholder-logo.png',
      createdAt: '2026-03-23T07:45:00.000Z',
      status: 'Under Review',
    },
    {
      id: 'partner-2',
      organizationName: 'Faith Impact Network',
      contactPerson: 'Jean Claude',
      phone: '0788000011',
      email: 'jean@fin.org',
      country: 'Rwanda',
      city: 'Huye',
      partnershipType: 'Training',
      website: 'https://example.com',
      vision: 'Leadership development and training partnership.',
      proposal: 'We propose a quarterly training partnership for leaders and volunteers.',
      logoUrl: '/placeholder-logo.png',
      createdAt: '2026-03-26T14:10:00.000Z',
      status: 'New',
    },
  ],
  prayerRequests: [
    {
      id: 'prayer-1',
      fullName: 'Deborah Uwineza',
      email: 'deborah@example.com',
      phone: '0788000020',
      message: 'Please pray for healing and peace in my family.',
      createdAt: '2026-03-27T12:20:00.000Z',
      status: 'New',
    },
    {
      id: 'prayer-2',
      fullName: 'Patrick M.',
      email: 'patrick@example.com',
      phone: '0788000021',
      message: 'Prayer for work and direction in ministry.',
      createdAt: '2026-03-27T15:45:00.000Z',
      status: 'Prayed For',
    },
  ],
  giving: [
    {
      id: 'giving-1',
      fullName: 'Aline Mukamana',
      email: 'aline@example.com',
      phone: '0788000001',
      purpose: 'Tithe',
      paymentCategory: 'mobile-money',
      amount: 25000,
      currency: 'RWF',
      createdAt: '2026-03-27T09:10:00.000Z',
      status: 'Recorded',
    },
    {
      id: 'giving-2',
      fullName: 'Samuel Ndayishimiye',
      email: 'samuel@example.com',
      phone: '0788000002',
      purpose: 'Project Support',
      paymentCategory: 'credit-card',
      amount: 150,
      currency: 'USD',
      createdAt: '2026-03-27T12:40:00.000Z',
      status: 'Recorded',
    },
    {
      id: 'giving-3',
      fullName: 'Grace Uwera',
      email: 'grace@kba.org',
      phone: '0788000010',
      purpose: 'Offering',
      paymentCategory: 'mobile-money',
      amount: 40000,
      currency: 'RWF',
      createdAt: '2026-03-28T08:00:00.000Z',
      status: 'Recorded',
    },
  ],
  notificationSettings: {
    channels: {
      inApp: true,
      email: true,
      sms: false,
    },
    triggers: {
      membership: true,
      partnership: true,
      prayerRequest: true,
      giving: true,
      projectUpdate: false,
      eventUpdate: true,
      mediaUpload: false,
    },
  },
}
